version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - app
    container_name: api-lesson-nginx
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: api-lesson-app
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: api-laravel-lesson
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8801:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: api_lesson_db
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
